### ISSUE TITLE
Academic communication

### ISSUE THREAD

**Issue by yanghaiyu2020** [ayberkuckun/DL-Approach-on-SEI-Using-UMOP-Characteristics#1]
What is the environment in which this repository code is run？

**Comment by ayberkuckun** [comment]
Colab Python 3.6 and MATLAB[R2020b]

**Comment by yanghaiyu2020** [comment]
Thank you very much for your reply. I'm trying to reproduce it. Do you have more information about SEI？

**Comment by ayberkuckun** [comment]
No worries! For the literature search, you can check the final report and articles in their corresponding folders. Unfortunately, I only have access to what I have in this repo, others were deleted. I hope you can progress it further!

**Comment by yanghaiyu2020** [comment]
Thank you, too. If you have any ideas in the future, we can exchange them.
